FROM node:16-alpine
USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./
RUN chmod a+x /home/node/app/node_modules/.bin/react-scripts
CMD ["npm", "start"]