sudo: required
services:
  - docker
before_install:
  - docker build -t thomasburke9891/react-test -f ./client/Dockerfile.dev ./client
 script:
  - docker run -e CI=true thomasburke9891/react-test npm test
after_success:
  - docker build -t thomasburke9891/multi-client ./client
  - docker build -t thomasburke9891/multi-nginx ./nginx
  - docker build -t thomasburke9891/multi-server ./server
  - docker build -t thomasburke9891/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push thomasburke9891/multi-client
  - docker push thomasburke9891/multi-nginx
  - docker push thomasburke9891/multi-server
  - docker push thomasburke9891/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-915955328185'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY